mainPages = [
    "/sariyer-haberleri",
    "/ekonomi",
    "/yasam",
    "/siyaset",
    "/roportaj",
    "/emlak",
    "/aktuel",
    "/alt-mansetler",
    "/saglik",
    "/kose-yazilari-arsiv",
    "/kose-yazilari",
    "/kultur-sanat",
    "/teknoloji",
    "/spor",
    "/egitim",
    "/foto-galeri",
    "/guncel-haberler",
    "/magazin",
    "/turkiye-ve-dunya-gundemi ",
    "/video-galeri",
    "/son-dakika-haberi",
    "/gundem",
    "/sektor",
]

unWantedExtensions = [
        ".png",
        ".jpg",
        ".jpeg",
        ".webp",
        ".JPG",
        ".PNG",
        ".JPEG",
        ".WEBP",
        ]